import Nav from '@/components/Nav'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { CONTENT_WEBSITE_LINKS } from '@/content/navContent'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='scroll-smooth'>
      <body className={inter.className + ' theme-mintset bg-neutralBg text-onNeutralBg light'}>
        {/* <Nav logoUrl={'/mintsetLogoBlack.svg'} logoDarkUrl={'/mintsetLogoWhite.svg'} links={CONTENT_WEBSITE_LINKS}/> */}
        
        {children}
      </body>
    </html>
  )
}
